---
deployment:
  tasks:
    # 1. Čiščenje starega (varnostno)
    - /bin/rm -rf /home/orakleum/public_html/SISTEM
    - /bin/rm -rf /home/orakleum/public_html/ADAPTER
    
    # 2. Kopiranje sveže verzije (vse iz repozitorija gre v public_html)
    - /bin/cp -Rf ./* /home/orakleum/public_html/
    
    # 3. Odstranitev konfiguracijskih datotek z interneta (varnost!)
    - /bin/rm -f /home/orakleum/public_html/.cpanel.yml
    - /bin/rm -f /home/orakleum/public_html/.git*
    
    # 4. Popravljanje dovoljenj (CageFS)
    - /bin/find /home/orakleum/public_html -type d -exec chmod 755 {} \;
    - /bin/find /home/orakleum/public_html -type f -exec chmod 644 {} \;