<?php declare(strict_types=1);
function gp($i,$g){
  $a='modul_' . $g . '_a'; $b='_' . $g . '_i'; $c='_' . $g . '_d';
  return '<?php\ndeclare(strict_types=1);\n$h=[__DIR__ . "/../../Modul_Bridge/modul_bridge.php"]; $f=false; foreach($h as $p){if(file_exists($p)){require_once $p; $f=true; break;}} if(!$f){header("Content-Type: application/json"); echo json_encode(["e"=>"Bridge"]); exit;} if(!function_exists("ru")){function ru($d,$s=""){return["st"=>"ok","c"=>200,"sp"=>$s,"v"=>$d];} function er($m,$k=400){return["st"=>"err","c"=>$k,"sp"=>$m,"v"=>[]];}} function ' . $a . '($a,$d=[]){if(!Modul_Bridge::vloga_preveri("S0")) return er("Zaprto",403); return match($a){"info"=>' . $b . '($d), "domov"=>' . $c . '($d), default=>er("?",400)};} function ' . $b . '($d){$u=Modul_Bridge::uporabnik_pridobi(); return ru(["n"=>"' . $i . '","i"=>"' . $g . '","v"=>"1.0","k"=>"' . $g . '","o"=>"' . $i . '","u"=>($u["ime"]??"Gost"),"a"=>["info","domov"]], "i");} function ' . $c . '($d){return ru(["s"=>"Pozdravljen v ' . $i . '!","t"=>time(),"i"=>"' . $g . '"], "d");} if(basename($_SERVER["SCRIPT_FILENAME"]??"")==="modul.php" && !defined("SISTEM_OBSTAJA")){$q=$_REQUEST["akcija"]??"domov"; $o=' . $a . '($q,$_REQUEST); header("Content-Type: application/json; charset=utf-8"); echo json_encode($o,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);} ';
}
function gm($i,$g,$k){
  return json_encode(["_id"=>$g,"_v"=>"1.0","m"=>["id"=>$g,"i"=>$i,"t"=>"zb","n"=>1,"v"=>"1.0","a"=>1,"s"=>"modul.php","o"=>"Modul $i - $k.","st"=>"raz","d"=>0,"z"=>0],"d"=>["l"=>"S0","p"=>"os","j"=>1,"pl"=>0,"ot"=>0,"v"=>"vsi","pz"=>["branje"]],"c"=>["o"=>1,"t"=>3600],"u"=>["ip"=>1,"ik"=>"📖","b"=>"#8bf","k"=>$k,"dp"=>["s"],"tg"=>[$g],"jz"=>["sl"]],"x"=>["t"=>"ui","ao"=>0,"i"=>null,"oz"=>0,"pr"=>50,"bs"=>null],"mg"=>["o"=>0,"z"=>null],"in"=>["c"=>null],"lg"=>["o"=>1,"l"=>"info"],"ca"=>["u"=>date("c"),"p"=>date("c"),"z"=>null]],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);
}
$r=__DIR__; $p=$r.'/MODULI iz PROJEKTA';
$k=array_filter(glob($r.'/*',GLOB_ONLYDIR), fn($d)=>!in_array(basename($d),['Modul_Bridge','PWA manifesti','MODULI iz PROJEKTA']));
echo "=== GENERATOR ===\n"; $u=0; $m=0;
echo "--- MANJKAJOCI modul.php ---\n";
foreach($k as $kp){ $kat=basename($kp); foreach(glob($kp.'/*',GLOB_ONLYDIR) as $mp){ $ime=basename($mp); $ph=$mp.'/modul.php'; $id=strtolower(preg_replace('/[^a-zA-Z0-9]/','',$ime)); if(file_exists($ph)) continue; $mat=null; foreach([$p."/$ime/modul.php",$p."/$ime/modul_$id.php",$p."/$kat/$ime/modul.php"] as $s){ if(file_exists($s)){ $mat=file_get_contents($s); echo "  KOPIRAN: $kat/$ime\n"; break; }} if($mat){ $mat=str_replace(["__DIR__ . '/../Modul_Bridge/modul_bridge.php'","__DIR__ . '/../../Modul_Bridge/modul_bridge.php'"], "__DIR__ . '/../../Modul_Bridge/modul_bridge.php'", $mat); file_put_contents($ph,$mat); $u++; } else { file_put_contents($ph,gp($ime,$id,$kat)); echo "  GENERIRAN: $kat/$ime\n"; $u++; }}}
echo "\n--- POPRAVLJANJE MANIFESTOV ---\n";
foreach($k as $kp){ $kat=basename($kp); foreach(glob($kp.'/*',GLOB_ONLYDIR) as $mp){ $ime=basename($mp); $id=strtolower(preg_replace('/[^a-zA-Z0-9]/','',$ime)); $mf=$mp.'/podatki/manifest.json'; if(!file_exists($mf)){ $man=gm($id,$ime,$kat); if(!is_dir($mp.'/podatki')) mkdir($mp.'/podatki',0755,true); file_put_contents($mf,$man); echo "  MANIFEST: $kat/$ime\n"; $m++; continue; } $j=json_decode(file_get_contents($mf),true); if(!$j){ echo "  NAPAČEN JSON: $kat/$ime\n"; continue; } if(!isset($j['_id']) && isset($j['id'])){ $n=cm($j,$id,$ime,$kat); file_put_contents($mf,json_encode($n,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)); echo "  POPRAVLJEN: $kat/$ime\n"; $m++; } }}
echo "\n=== KONEC ===\n"; echo "modul.php: $u | manifesti: $m\n";
