#!/usr/bin/env python3
"""
konfiguracija_modulov.py
=========================
Centralna konfiguracija vseh modulov po kategorijah.
Pot: MODULI/[Kategorija]/[ImeModula]/
"""

# Format: (ImeModula, opis, opcije)
# opcije so enake kot v generiraj_modul()

MODULI_PO_KATEGORIJAH = {

    "Univerzalno": [
        ("Aeternum",        "Večnost — arhivirane resnice, časovne dimenzije in kozmična zavest.",
         {"ikona": "♾️",  "barva": "#c4b5fd", "tags": ["vecnost", "kozmos", "zavest"]}),
        ("Aetheris",        "Eter in višje ravni — energijsko polje, avra, barvna analiza in čiščenje polja.",
         {"ikona": "💚",  "barva": "#67e8f9", "tags": ["eter", "avra", "energija"]}),
        ("AlchymiaAurea",   "Zlata alkimija — hermetični procesi, transmutacija snovi in duha.",
         {"ikona": "🜄",  "barva": "#fbbf24", "tags": ["alkimija", "hermetika", "zlato"]}),
        ("AuroraMystica",   "Mistična zora — prehodna stanja zavesti, jutranje rituale in prebujenje.",
         {"ikona": "🌅",  "barva": "#f0abfc", "tags": ["zora", "prebujenje", "ritual"]}),
        ("Celestara",       "Nebesna modrost — zvezde, ozvezdja, planetarne ure in kozmični ritmi.",
         {"ikona": "🌟",  "barva": "#c4b5fd", "tags": ["zvezde", "nebo", "planeti"]}),
        ("CorpusMysticum",  "Mistično telo — enciklopedija ezoteričnih znanj, simbolov in tradicij.",
         {"ikona": "📚",  "barva": "#a78bfa", "tip": "izvajalec", "nivo": 3, "tags": ["enciklopedija", "ezoterija"]}),
        ("Crystallum",      "Kristali — lastnosti, energije in uporaba kristalnih kamnin.",
         {"ikona": "💎",  "barva": "#e879f9", "tags": ["kristali", "kamni", "energija"]}),
        ("Energetica",      "Energijske prakse — delo z energijo, bioenergetika in energijska polja.",
         {"ikona": "⚡",  "barva": "#fde68a", "tags": ["energija", "bioenergetika", "polje"]}),
        ("GeometriaSacra",  "Sveta geometrija — kozmični vzorci, mandala, Flor življenja in fraktali.",
         {"ikona": "🔯",  "barva": "#6ee7b7", "tags": ["geometrija", "mandala", "fraktal"]}),
        ("Mystaia",         "Notranji misteriji — iniciacije, mistični poti in notranje transformacije.",
         {"ikona": "🌀",  "barva": "#818cf8", "tags": ["misteriji", "iniciacija", "transformacija"]}),
        ("Occultum",        "Okultne vede — skrito znanje, magijski sistemi in ezoterika.",
         {"ikona": "🔮",  "barva": "#6d28d9", "minimalna_vloga": "S2", "tags": ["okultno", "magija", "skrito"]}),
        ("QuantumMystica",  "Kvantna mistika — presečišče kvantne fizike in duhovnih resnic.",
         {"ikona": "⚛️",  "barva": "#67e8f9", "tags": ["kvantno", "fizika", "duhovno"]}),
        ("Synera",          "Sinergija zavesti — analiza kompatibilnosti in energijski vzorci v razmerjih.",
         {"ikona": "🔮",  "barva": "#e879f9", "minimalna_vloga": "S3", "placljivo": True,
          "tip": "izvajalec", "nivo": 3, "tags": ["sinastria", "razmerja", "vip"]}),
        ("Tarot",           "Tarot — arhetipske karte, razlage in globinska simbolika.",
         {"ikona": "🃏",  "barva": "#f59e0b", "tip": "izvajalec", "nivo": 3, "tags": ["tarot", "karte", "arhetip"]}),
        ("Transmutaria",    "Notranja preobrazba — alkimija duše, proces osebne transformacije.",
         {"ikona": "⚗️",  "barva": "#f59e0b", "tags": ["transmutacija", "preobrazba", "alkimija"]}),
        ("VibraMystica",    "Kozmične vibracije — zvočno zdravljenje, frekvenčna terapija in mantre.",
         {"ikona": "🎵",  "barva": "#c084fc", "tags": ["vibracija", "zvok", "frekvenca"]}),
        ("ViaAnimae",       "Pot duše — karmični vzorci, namen duše in akašični zapisi.",
         {"ikona": "🕊️",  "barva": "#f0abfc", "potrebuje": ["datum_rojstva"], "tags": ["karma", "dusa", "akaski"]}),
        ("Lunaris",         "Lunarne energije — lunine faze, rituali in ženski cikli.",
         {"ikona": "🌙",  "barva": "#818cf8", "tags": ["luna", "faze", "ritual"]}),
        ("NadaBrahma",      "Svete frekvence — zvočne vibracije, nada yoga in kozmični zvok.",
         {"ikona": "🎶",  "barva": "#a78bfa", "tags": ["nada", "zvok", "frekvenca", "yoga"]}),
    ],

    "Antika": [
        ("Kemetica",        "Egipčanske skrivnosti — hermetizem, hieroglifi in starodavna modrost Kemeta.",
         {"ikona": "𓂀",  "barva": "#d97706", "tags": ["egipt", "kemet", "hermetika"]}),
        ("MeduNeter",       "Hieroglifi — sveto egipčansko pismo, simboli in njihov mistični pomen.",
         {"ikona": "𓇋",  "barva": "#fbbf24", "tags": ["hieroglifi", "pisava", "egipt"]}),
        ("Neteru",          "Egipčanska božanstva — panteон bogov in boginj starodavnega Egipta.",
         {"ikona": "🦅",  "barva": "#f59e0b", "tags": ["bogovi", "egipt", "panteon"]}),
        ("Duat",            "Pot skozi podzemlje — egipčanska knjiga mrtvih, Amduat in pot duše.",
         {"ikona": "⚖️",  "barva": "#374151", "tags": ["podzemlje", "duat", "smrt", "dusa"]}),
        ("Heka",            "Magija in zaščita — egipčanska magija, zaščitni simboli in rituali.",
         {"ikona": "𓂋",  "barva": "#6d28d9", "minimalna_vloga": "S1", "tags": ["magija", "zascita", "egipt"]}),
        ("Oneiros",         "Razlaga sanj — grška tradicija sanjskih prerokb in interpretacij.",
         {"ikona": "💤",  "barva": "#6d28d9", "tags": ["sanje", "grcija", "prerokba"]}),
        ("Mythos",          "Grška mitologija — heroji, bogovi in kozmogonija stare Grčije.",
         {"ikona": "⚡",  "barva": "#3b82f6", "tags": ["grcija", "mitologija", "bogovi"]}),
        ("Labyrinthos",     "Labirint zavesti — grški labirint kot metafora duhovne poti.",
         {"ikona": "🌀",  "barva": "#6ee7b7", "tags": ["labirint", "grcija", "pot"]}),
        ("Daimon",          "Duhovni vodniki — grška tradicija osebnega duha in notranjega vodnika.",
         {"ikona": "👁️",  "barva": "#c4b5fd", "tags": ["daimon", "vodnik", "duh", "grcija"]}),
    ],

    "Indija": [
        ("Pranayama",       "Dihalne tehnike — pranajama, kontrola diha in vitalne energije.",
         {"ikona": "🧘",  "barva": "#6ee7b7", "tags": ["dihanje", "prana", "yoga"]}),
        ("ChakraVidya",     "Sistem čaker — energijska telesa, čakre in kundalini.",
         {"ikona": "🔆",  "barva": "#f59e0b", "tags": ["cakre", "kundalini", "energija"]}),
        ("Jyotisha",        "Vedska astrologija — jyotish, nakshatre in vedske planetarne energije.",
         {"ikona": "⭐",  "barva": "#fbbf24", "tip": "sestavljalec", "nivo": 2,
          "potrebuje": ["datum_rojstva", "kraj_rojstva"], "tags": ["jyotish", "astrologija", "vedska"]}),
        ("Dhyana",          "Meditacija — vipassana, transcendentalna in vedantska meditacija.",
         {"ikona": "🪷",  "barva": "#f0abfc", "tags": ["meditacija", "vipassana", "vedanta"]}),
        ("Ayurveda",        "Ajurveda — starodavna indijska medicina, doshe in ravnovesje.",
         {"ikona": "🌿",  "barva": "#4ade80", "tags": ["ajurveda", "dosa", "medicina"]}),
    ],

    "Kitajska": [
        ("Qi",              "Življenjska energija — qi gong, življenjska sila in kitajska energetika.",
         {"ikona": "🐉",  "barva": "#34d399", "tags": ["qi", "qigong", "energija"]}),
        ("ZhongYi",         "Tradicionalna kitajska medicina — meridianski sistem, akupunktura in fitoterapija.",
         {"ikona": "☯️",  "barva": "#6ee7b7", "tags": ["tcm", "meridiani", "akupunktura"]}),
        ("IChing",          "Knjiga sprememb — I Ching, trigrami, heksagrami in kitajska prerokba.",
         {"ikona": "☯️",  "barva": "#fbbf24", "tags": ["iching", "heksagram", "prerokba"]}),
        ("Tao",             "Pot Tao — taoizem, wu wei, naravna pot in ravnovesje nasprotij.",
         {"ikona": "🌊",  "barva": "#67e8f9", "tags": ["tao", "taoizem", "ravnovesje"]}),
        ("WuXing",          "Pet elementov — les, ogenj, zemlja, kovina, voda in njihove interakcije.",
         {"ikona": "🔥",  "barva": "#f59e0b", "tags": ["elementi", "wuxing", "kitajska"]}),
    ],

    "Japonska": [
        ("Shinto",          "Šintoizem — japonska naravna duhovnost, kami in svetišča.",
         {"ikona": "⛩️",  "barva": "#f0abfc", "tags": ["shinto", "kami", "japonska"]}),
        ("Reiki",           "Reiki — japonska tehnika energijskega zdravljenja in ravnovesja.",
         {"ikona": "✋",  "barva": "#67e8f9", "tags": ["reiki", "zdravljenje", "energija"]}),
        ("Kotodama",        "Moč besed — japonska tradicija zvočne magije in moči besed.",
         {"ikona": "🎵",  "barva": "#c084fc", "tags": ["kotodama", "besede", "zvok"]}),
        ("Yume",            "Svet sanj — japonska tradicija sanjske interpretacije in yume no michi.",
         {"ikona": "💤",  "barva": "#6d28d9", "tags": ["sanje", "japonska", "yume"]}),
    ],

    "Koreja": [
        ("Musok",           "Korejski šamanizem — mudang, duhovi prednikov in korejske duhovne prakse.",
         {"ikona": "🥁",  "barva": "#f59e0b", "tags": ["samanizem", "koreja", "mudang"]}),
        ("Hanbang",         "Tradicionalna korejska medicina — hanbang, zeliščarstvo in energijsko zdravljenje.",
         {"ikona": "🌿",  "barva": "#4ade80", "tags": ["medicina", "koreja", "zeliscje"]}),
    ],

    "HebrejskaMistika": [
        ("Kabbalah",        "Kabala — mistični judaizem, Ein Sof in kozmična struktura stvarnosti.",
         {"ikona": "✡️",  "barva": "#fbbf24", "minimalna_vloga": "S2", "tags": ["kabala", "judaizem", "mistika"]}),
        ("Sephirot",        "Drevo življenja — deset sefir, poti med njimi in kabalistična meditacija.",
         {"ikona": "🌳",  "barva": "#fbbf24", "minimalna_vloga": "S2", "tags": ["sefiroti", "drevo", "kabala"]}),
        ("Malakhim",        "Angelske hierarhije — angelski redi, arhangeli in nebeška hierarhija.",
         {"ikona": "👼",  "barva": "#fde68a", "tags": ["angeli", "arhangeli", "hierarhija"]}),
        ("Angelarium",      "Svet angelov — angelska sporočila, varstvo in komunikacija z angeli.",
         {"ikona": "🕊️",  "barva": "#fde68a", "varuh": "Arhangel Rafael", "tags": ["angeli", "varstvo", "sporocila"]}),
    ],

    "EvropaNordija": [
        ("Runir",           "Rune — nordijska runska pisava, Elder Futhark in runska magija.",
         {"ikona": "ᚱ",   "barva": "#6ee7b7", "tags": ["rune", "futhark", "nordijska"]}),
        ("Seidr",           "Nordijska magija — seidr, galdr, nordijska šamanistična tradicija.",
         {"ikona": "🌲",  "barva": "#4ade80", "minimalna_vloga": "S1", "tags": ["seidr", "galdr", "nordijska"]}),
    ],

    "EvropaSlovani": [
        ("Rodnoverje",      "Slovansko staroverstvo — predkrščanska slovanska duhovnost in bogovi.",
         {"ikona": "🌻",  "barva": "#fbbf24", "tags": ["slovani", "staroverstvo", "bogovi"]}),
        ("Perun",           "Perun — slovansko božanstvo groma, pravice in nebesnih sil.",
         {"ikona": "⚡",  "barva": "#3b82f6", "tags": ["perun", "slovani", "grom"]}),
        ("Veles",           "Veles — slovansko božanstvo podzemlja, narave in modrosti.",
         {"ikona": "🐍",  "barva": "#374151", "tags": ["veles", "slovani", "podzemlje"]}),
        ("Kresnik",         "Slovenska mistika — Kresnik, Kurent in slovensko duhovno izročilo.",
         {"ikona": "🔥",  "barva": "#f59e0b", "tags": ["kresnik", "slovenija", "izrocilo"]}),
    ],

    "EvropaKelti": [
        ("Ogham",           "Keltska pisava — oghamska abeceda in njena duhovna simbolika.",
         {"ikona": "🌿",  "barva": "#4ade80", "tags": ["ogham", "kelti", "pisava"]}),
        ("Druidica",        "Druidizem — druidska tradicija, naravna duhovnost in keltska modrost.",
         {"ikona": "🌳",  "barva": "#6ee7b7", "minimalna_vloga": "S1", "tags": ["druidi", "kelti", "narava"]}),
        ("Avalon",          "Keltski misteriji — Avalon, Arturjanska legenda in keltski mistični svet.",
         {"ikona": "⚔️",  "barva": "#818cf8", "tags": ["avalon", "artur", "kelti"]}),
    ],

    "AmerikaMezoamerika": [
        ("Anahuac",         "Mezoamerične skrivnosti — maya, azteka in olmeka kozmologija.",
         {"ikona": "🌞",  "barva": "#f59e0b", "tags": ["maya", "azteka", "mezoamerika"]}),
        ("Maya",            "Maya — mayanski koledar, Tzolkin, Long Count in kozmični cikli.",
         {"ikona": "📅",  "barva": "#d97706", "tags": ["maya", "koledar", "tzolkin"]}),
        ("Azteca",          "Azteka — aztekski panteon, kozmogonija in duhovna tradicija.",
         {"ikona": "🦅",  "barva": "#dc2626", "tags": ["azteka", "panteon", "tradicija"]}),
        ("Nahuatl",         "Nahuatl — jezik in modrost nahuatl tradicije, tonal in nagual.",
         {"ikona": "🌿",  "barva": "#4ade80", "tags": ["nahuatl", "tonal", "nagual"]}),
    ],

    "AmerikaAmazonija": [
        ("AmazoniaSacra",   "Amazonski šamanizem — rastlinska medicina, ayahuasca in duhovni rituali.",
         {"ikona": "🌿",  "barva": "#4ade80", "minimalna_vloga": "S1",
          "tags": ["amazonija", "samanizem", "rastline"]}),
    ],

    "Samanizem": [
        ("Shamanica",       "Šamanizem — šamanski rituali, bobni, duhovna potovanja in zdravljenje.",
         {"ikona": "🥁",  "barva": "#d97706", "tags": ["samanizem", "ritual", "zdravljenje"]}),
        ("Animaris",        "Živalski vodniki — totemske živali, šamanistična tradicija živalskih duhov.",
         {"ikona": "🐺",  "barva": "#6ee7b7", "tags": ["totem", "zival", "vodnik"]}),
        ("ViaAnimae",       "Pot duše — šamanistična tradicija poti duše in medduhovnih potovanj.",
         {"ikona": "🕊️",  "barva": "#f0abfc", "tags": ["dusa", "pot", "samanizem"]}),
    ],

    "Znanost": [
        ("Nasa",            "NASA senzorji — sončeva aktivnost (NASA DONKI), geomagnetna aktivnost (NOAA SWPC).",
         {"ikona": "🛰️",  "barva": "#67e8f9", "javno_vidno": False, "vidnost": "skriti",
          "ima_prikaz": False, "izvajanje_tip": "cron", "api_only": True,
          "interval": 900, "ob_zagonu": True, "prioriteta": 100,
          "cache_ttl": 900, "cache_strategija": "casovna", "vir": "zunanji_api",
          "pise_v": ["PODATKI/moduli/nasa/snapshot.json", "PODATKI/moduli/nasa/zgodovina.json"],
          "tags": ["nasa", "senzorji", "vreme", "geomagnetno"]}),
        ("SolarniPojavi",   "Sončevi pojavi — analiza sončevih izbruhov, CME in njihov vpliv.",
         {"ikona": "☀️",  "barva": "#fbbf24", "bere_iz": ["nasa"], "tags": ["sonce", "cmE", "pojavi"]}),
        ("Stelaris",        "Zvezdno nebo — astrološki motor, natalni horoskop, tranziti in aspekti.",
         {"ikona": "🌌",  "barva": "#818cf8", "tip": "sestavljalec", "nivo": 2,
          "potrebuje": ["datum_rojstva", "kraj_rojstva"], "tags": ["astrologija", "horoskop", "planeti"]}),
        ("CosmicaScientia", "Kozmična znanost — bioritem, Schumannove resonance in kozmobiologija.",
         {"ikona": "🔭",  "barva": "#818cf8", "bere_iz": ["nasa"], "tags": ["bioritem", "schumann", "kozmobiologija"]}),
    ],

    "Knjiznice": [
        ("Codex",           "Univerzalni kodeks — enciklopedija vseh tradicij, pojmov in simbolov.",
         {"ikona": "📖",  "barva": "#c9a96e", "tip": "izvajalec", "nivo": 3, "tags": ["kodeks", "enciklopedija"]}),
        ("CodexAntiqua",    "Starodavni kodeksi — zbirka starih tekstov, prepisov in komentarjev.",
         {"ikona": "📜",  "barva": "#d97706", "tags": ["starodavno", "tekst", "kodeks"]}),
        ("UmbraeCodex",     "Kodeks senc — senca po Jungu, integracija temne strani.",
         {"ikona": "🌑",  "barva": "#374151", "minimalna_vloga": "S2", "tags": ["senca", "jung", "integracija"]}),
        ("Orakleum",        "Oraklji in prerokbe — zbirka orakljev različnih tradicij.",
         {"ikona": "👁️",  "barva": "#6d28d9", "tags": ["orakelj", "prerokba"]}),
        ("OraculumVisionis","Vizije in prerokbe — vizionarska stanja, prerokbe in duhovna videnja.",
         {"ikona": "🔮",  "barva": "#8b5cf6", "tags": ["vizija", "prerokba", "videnje"]}),
    ],

    "Prihodnost": [
        ("Hermetica",       "Hermetizem — hermetična filozofija, Corpus Hermeticum in Trismegist.",
         {"ikona": "⚕️",  "barva": "#fbbf24", "tags": ["hermetika", "trismegist", "filozofija"]}),
        ("Gnostica",        "Gnosticizem — gnostični miti, Demiurg in iskanje božanske iskre.",
         {"ikona": "✨",  "barva": "#818cf8", "minimalna_vloga": "S1", "tags": ["gnosticizem", "demiurg", "dusa"]}),
        ("Sufica",          "Sufizem — islamska mistika, zikr, derviški ples in Rumi.",
         {"ikona": "🌹",  "barva": "#f0abfc", "tags": ["sufizem", "zikr", "rumi"]}),
        ("Buddhica",        "Budizem — buda dharma, nirvana, meditacija in pot prebujenja.",
         {"ikona": "☸️",  "barva": "#fbbf24", "tags": ["budizem", "dharma", "meditacija"]}),
        ("TaoMystica",      "Taoizem — mistični taoizem, notranja alkimija in naravna pot.",
         {"ikona": "☯️",  "barva": "#67e8f9", "tags": ["taoizem", "alkimija", "narava"]}),
        ("CelticaMystica",  "Keltska mistika — globlja keltska ezoterika, druidska mistika.",
         {"ikona": "🍀",  "barva": "#4ade80", "tags": ["kelti", "mistika", "druidi"]}),
        ("SlavicaMystica",  "Slovanska mistika — predkrščanska slovanska magija in misteriji.",
         {"ikona": "🌻",  "barva": "#f59e0b", "tags": ["slovani", "magija", "misteriji"]}),
        ("AfricanaMystica", "Afriške tradicije — Yoruba, Voodoo, Ubuntu in afriška duhovna modrost.",
         {"ikona": "🥁",  "barva": "#d97706", "tags": ["afrika", "yoruba", "voodoo"]}),
        ("PolynesiaMystica","Polinezijska modrost — mana, tapu, Haka in polinezijska duhovna tradicija.",
         {"ikona": "🌺",  "barva": "#34d399", "tags": ["polinezija", "mana", "tapu"]}),
    ],
}
